### ISSUE TITLE
why pug instead of nunjucks?

### ISSUE THREAD

**Issue by lorvent** [evgeniy-vashchuk/x-project#1]
Hello,
I am genuinely interested in knowing why? can you please explain?

**Comment by evgeniy-vashchuk** [comment]
@lorvent Hey! Pug is one of the most popular HTML preprocessors, so I just picked him. For the current moment, Pug meets all my needs. Or you know some benefits of using Nunjucks?

**Comment by lorvent** [comment]
Hey, there is nothing like benefits but i find nunjucks syntax language is more elegant and same like laravel blade etc.
or simply put, it looks natural to me and others like pug looks like python and some clunky code styles to me..just my opinion.

and i always used only nunjucks

so wanted to get your perspective.

also, i really liked your repo for linting etc :)

**Comment by evgeniy-vashchuk** [comment]
> also, i really liked your repo for linting etc :)

I'm glad to hear that 😉
